apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: {{ .Values.secret.type }}
data:
  POSTGRES_DB: {{ .Values.secret.data.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.secret.data.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secret.data.POSTGRES_PASSWORD }}
