apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbService.name }}
spec:
  ports:
  - port: {{ .Values.dbService.port }}
  selector:
    app: {{ .Values.dbService.selector.app }}
  clusterIP: {{ .Values.dbService.clusterIP }}
