apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-storage
spec:
  storageClassName: manual  # Make sure this matches with your available StorageClasses
  accessModes:
    - ReadWriteOnce  # should match with your PersistentVolume
  resources:
    requests:
      storage: 1Gi
