apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: danielemuze/deel-project:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres-service"  # match the name of the postgres Service
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config  # match the name of the postgres ConfigMap
              key: POSTGRES_DB
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: web-storage
          mountPath: /var/lib/deel-project
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "0.5"
            memory: 1Gi
      volumes:
      - name: web-storage
        persistentVolumeClaim:
          claimName: web-storage

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-storage-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  # Ensure this matches with your PVC's storageClassName
  hostPath:  # This is just for demonstration and should not be used in production
    path: "/mnt/data/web-storage"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-storage
spec:
  storageClassName: manual  # Make sure this matches with your available StorageClasses
  accessModes:
    - ReadWriteOnce  # should match with your PersistentVolume
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  POSTGRES_DB: bXlkYXRhYmFzZQ== 
  POSTGRES_USER: bXl1c2Vy  
  POSTGRES_PASSWORD: bXlwYXNzd29yZA== 

---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
